package ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * Created by WangQing on 15/12/6.
 */
class HandlerFileUi extends JFrame {
    private JTextField loadingText;
    private JPanel panel1;
    private JProgressBar progressBar;

    public Container getHandlerFileUi() throws HeadlessException {
        Container container = getContentPane();

        panel1 = new JPanel();

        loadingText = new JTextField();

        loadingText.setHorizontalAlignment(SwingConstants.CENTER);

        panel1.add(loadingText);

        progressBar = new JProgressBar();

        progressBar.setAutoscrolls(true);

        panel1.add(progressBar);

        container.add(panel1);

        return container;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        loadingText = new JTextField();
        loadingText.setText("正在处理文件中,请稍后...");
        panel1.add(loadingText, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        progressBar = new JProgressBar();
        progressBar.setAutoscrolls(true);
        panel1.add(progressBar, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
