package ui;

import javax.swing.*;
import java.awt.*;

/**
 * Created by WangQing on 15/12/6.
 */
public class te {
    private JButton button1;
    private JPanel panel1;
    private JPasswordField passwordField1;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        button1 = new JButton();
        button1.setText("Button");
        panel1.add(button1, BorderLayout.NORTH);
        passwordField1 = new JPasswordField();
        panel1.add(passwordField1, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
